llms:
  main:
    type: 'groq'
    model_id: 'llama-3.3-70b-versatile'
    aws_region: 'us-east-1'
    temperature: 0

  fallback:
    type: 'groq'
    model_id: 'llama-3.3-70b-versatile'
    aws_region: 'us-east-1'
    temperature: 0

llm-tracing:
  type: 'langfuse' # 'langfuse' or 'none'
